[tool.poetry]
name = "pythonproject3"
version = "0.1.0"
description = ""
authors = ["Emma Deyneko <deynekochan@mail.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
